name: athkari
description: "athkari project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #rating: ^1.0.0-dev.1
  flutter_time_picker_spinner: ^2.0.0
  share_plus: ^10.1.0
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  #service_locater
  get_it: ^8.0.0

  shared_preferences: ^2.2.2
  go_router: ^14.1.4
  intl: ^0.19.0
  gradient_borders: ^1.0.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  easy_date_timeline: ^2.0.4
  flutter_bloc: ^8.1.6
  #database
  sqflite: ^2.4.1
  
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#Splash Screen
flutter_native_splash:
  background_image: "assets/images/splash_screen.png"
  fullscreen: true


  



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
           #style: italic

  
