name: athkari
description: "athkari project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#Splash Screen
flutter_native_splash:
  background_image: "assets/images/splash_screen.png"
  fullscreen: true


  



flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
           #style: italic

  
